### ISSUE TITLE
How to manage multiple slices 

### ISSUE THREAD

**Issue by 316953425** [Gradiant/5g-charts#196]
### Components and subsystems

slice
### Proposed functionality

hi, I install it follow the doc : https://gradiant.github.io/5g-charts/open5gs-ueransim-gnb.html
it works well and very good

In my us pod , it have two ue tun interface , but they use only one slice
<img width="682" alt="1731487406398" src="https://github.com/user-attachments/assets/ab50fa17-82a2-41e6-9082-0e6c705d75cf">

I want to use two slice，each ue tun interface use one slice , I guess the 5gSA-values.yaml file needs to be modified, but I can't find the documentation on how to modify it.
Could you tell me it ?
thanks 

my 5gSA-values.yaml
```
hss:
  enabled: false

mme:
  enabled: false

pcrf:
  enabled: false

smf:
  config:
    pcrf:
      enabled: false

sgwc:
  enabled: false

sgwu:
  enabled: false

amf:
  config:
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"

nssf:
  config:
    nsiList:
      - uri: ""
        sst: 1
        sd: "0x111111"

webui:
  ingress:
    enabled: false

populate:
  enabled: true
  initCommands:
  - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
  - open5gs-dbctl add_ue_with_slice 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
```
