### ISSUE TITLE
Open5gs Metrics don't work out of the box

### ISSUE THREAD

**Issue by akanok** [Gradiant/5g-charts#202]
I wanted to export metrics form Open5gs using the Prometheus Operator, this are the steps that I performed:

1. Install the helm chart:

```sh
helm install open5gs oci://registry-1.docker.io/gradiant/open5gs --version 2.2.0 --values custom_values.yml
```

My `custom_values.yml` looks like this

```yml
dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-dbctl
    tag: 0.10.3
    pullPolicy: IfNotPresent
  initCommands: []

# Common
mongodb:
  enabled: true
  auth:
    enabled: false
smf:
  enabled: true
  metrics:
    enabled: true
upf:
  enabled: true
  metrics:
    enabled: true
webui:
  enabled: true

# 4G
hss:
  enabled: true
  mongodb:
    enabled: false
  config:
    logLevel: info
mme:
  enabled: true
  config:
    logLevel: info
    gummeiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        mme_gid: 2
        mme_code: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac: [1]
    networkName: internet
pcrf:
  enabled: true
  mongodb:
    enabled: false
  config:
    logLevel: info
sgwc:
  enabled: true
  config:
    logLevel: info
  pfcp:
    client:
      sgwuList:
        - address: "" # if empty default is autogenerated open5gs svc fullname
          apn: ["internet"]
sgwu:
  enabled: true
  config:
    logLevel: info

# 5G
amf:
  enabled: true
  metrics:
    enabled: true
  config:
    logLevel: info
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "0x111111"
    networkName: internet
ausf:
  enabled: true
  config:
    logLevel: info
bsf:
  enabled: true
  config:
    logLevel: info
nrf:
  enabled: true
  config:
    logLevel: info
    servingList:
      - plmn_id:
          mcc: 999
          mnc: 70
nssf:
  enabled: true
  config:
    logLevel: info
    nsiList:
      - uri: ""
        sst: 1
        sd: "0x111111"
pcf:
  enabled: true
  metrics:
    enabled: true
  mongodb:
    enabled: false
  config:
    logLevel: info
scp:
  enabled: true
  mongodb:
    enabled: false
  config:
    logLevel: info
udm:
  enabled: true
  config:
    logLevel: info
udr:
  enabled: true
  mongodb:
    enabled: false
  config:
    logLevel: info
```

I enable metrics for SMF, UPF, AMF and PCF

```yml
metrics:
  enabled: true
```

> [!NOTE]
> 
>  I was not able to set the _serviceMonitor_ as _enabled_ in `custom_values.yml`, under each of the four NF, how it's stated in [#136](https://github.com/Gradiant/5g-charts/issues/136#issuecomment-1718890445) and suggested in [#182](https://github.com/Gradiant/5g-charts/issues/182). Because `serviceMonitor` is not a valid configuration field. I probably got something wrong but I don't know what.
>
> ```yml
>  metrics:
>    enabled: true
>    serviceMonitor:
>      enabled: true
> ```
>
> But in the end I didn't need this additional configuration to export metrics in Prometheus Operator.

2. Install the Prometheus Operator

```sh
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install kube-prometheus-stack --create-namespace --namespace kube-prometheus-stack prometheus-community/kube-prometheus-stack

# (Optional) Forward Prometheus web-ui port
kubectl port-forward -n /kube-prometheus-stack svc//kube-prometheus-stack-prometheus 9090:9090
```

3. Create a ServiceMonitor

I would expect Prometheus to automatically discover the Open5gs services exposing metrics on `/metrics`. But it didn't work.

So I create, and installed, my own ServiceMonitor:

```yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-servicemonitor
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      targetPort: metrics
      path: /metrics
      interval: 5s
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: open5gs
  fallbackScrapeProtocol: PrometheusText1.0.0
```

At first I was having problems because I use _Prometheus 3.0_, which by default
rejects the scrape if an invalid/empty/missing `Content-Type` header is found while querying the `/metrics` endpoint.

And the Open5gs `/metrics` endpoint doesn't set any `Content-Type` header in the response.

I had to configure the [fallback scrape protocol](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#monitoring.coreos.com/v1.ScrapeProtocol) to `PrometheusText1.0.0` so that the response is parsed as text without checking the headers.

```yml
spec:
  fallbackScrapeProtocol: PrometheusText1.0.0
```

Was this the intended way to export metrics?
Did I get something wrong?
